export enum EmploymentType {
    PART_TIME = 'PART_TIME',
    FULL_TIME = 'FULL_TIME',
    COMMISSION = 'COMMISSION',
    SELF_EMPLOYED = 'SELF_EMPLOYED',
    TEMPORARY = 'TEMPORARY',
    CASUAL = 'CASUAL',
    CONTRACT = 'CONTRACT',
    FREELANCE = 'FREELANCE',
    INTERNSHIP = 'INTERNSHIP'
}
